# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_chains <- function(y, x, X_t_X, X_t_y, n_samp, n_thin, n, p, M, init_alpha, init_beta, init_psi, init_sigma, init_lambda, init_gamma, init_prop_sd, tuning_time, tuning_freq, verbose) {
    .Call('_NGlm_get_chains', PACKAGE = 'NGlm', y, x, X_t_X, X_t_y, n_samp, n_thin, n, p, M, init_alpha, init_beta, init_psi, init_sigma, init_lambda, init_gamma, init_prop_sd, tuning_time, tuning_freq, verbose)
}

